load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@rust//:toolchain.bzl", "rust_toolchain")

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    interpreter = "python3",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

rust_toolchain.nightly.with_version("2026-02-11").default(
    name = "rust",
    visibility = ["PUBLIC"],
)
